l_english:
 SETTING_AUTOSAVE:0 "Intervalo de salvamento automático"
 SETTING_DEBUG_SAVES:0 "Número de salvamentos com debug"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "Dicas Desativadas"
 SETTING_FOCUS_ON_COMBAT:0 "Foco no combate"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "Fronteiras do Reino na Costa"
 SETTING_TOOLTIP_DELAY:1 "Atraso na Aba de Dicas"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\n Define o atraso antes que a aba apareça."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Atraso do Destravamento"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n Define o atraso antes que a aba seja liberada."
 SETTING_TOOLTIP_LOCK_TIME:0 "Atraso de Trava"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n Define o atraso antes que a aba seja travada."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Atraso de Aba Travada"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n Define o atraso antes da aba ser travada quando outra aba ja está aberta."
 # Audio
 SETTING_Sound_Effects:1 "Todos os Efeitos Sonoros"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Sound Effects Volume\n#!Define o volume de TODOS os efeitos sonoros."
 SETTING_Ambience:0 "Ambientação"
 SETTING_Ambience_TOOLTIP:1 "#T Ambience Volume\n#!Define o volume da ambientação."
 SETTING_TOOLTIP_MODE:1 "Modo de Configuração de Abas"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\n Define a maneira que as abas "travam," permitindo abas dentro de abas."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Tendencia do Mouse"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\n Abas automaticamente travam no lugar até que o cursor saia delas."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Tranca de Ação"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n Pressione #V Botão do Meio do Mouse#! para travar e destravar abas."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Tempo para Travamento"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\n Abas travam em seu lugar se o cursos não se mover por um curto periodo. #weak (Configuração padrão.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Misc"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Abas"
 SETTINGS_CATEGORY_SFX:0 "Efeitos Sonoros Específicos"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Geral"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controles do Mapa"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Salvar Jogos"
 SETTINGS_CATEGORY_LANGUAGE:0 "Língua"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avançado"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Retratos"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Mostrar doenças e ferimentos gráficos"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n Define se doenças e ferimentos gráficos serão visíveis nos retratos dos personagens."
 NEVER:0 "Nunca"
 MONTHLY:0 "A cada mês"
 HALFYEAR:0 "A cada 6 meses"
 YEARLY:0 "A cada ano"
 FIVE_YEAR:0 "A cada 5 anos"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Mostrar Aviso Reativo"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\n Define se o jogo deve mostrar Avisos de tutorial reagindo à como você joga. Útil para jogadores novos ao Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Mostrar Sugestões"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\n Define se o jogo deve sugerir algo para fazer em intervalos regulares. Útil para jogadores novos ao Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Restabelecer Aviso Reativo"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Restabelecer Aviso Reativo#!\n Avisos Reativos anteriormente vistos serão mostrados novamente."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Restabelecer Aviso Reativo"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Você tem certeza que deseja Restabelecer o Aviso Reativo?"
 SETTING_ADVANCED_SHADERS:0 "Efeitos Avançados de Shader"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Efeitos Avançados de Shader\n#! Essa opção vai habilitar efeitos avançados de shader.\n\n Desliga-la pode aumentar o desempenho ao custo de fazer alguns efeitos (como terreno e água) aparentarem pior"
 BASED_ON_ZOOM_LEVEL:0 "Dinâmico"
 ALWAYS_HIDE:0 "Sempre Esconder"
 ALWAYS_SHOW:0 "Sempre Mostrar"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Fronteiras Costais"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\n Essa opção vai controlar quando as fronterias costais do reino devem ser mostradas.\n Se $BASED_ON_ZOOM_LEVEL$ então elas serão escondidas baseado no nível de detalhe do zoom.\n\n Escolhendo $ALWAYS_SHOW$ ou $ALWAYS_HIDE$ pode aumentar o desempenho ao custo que as fronteiras costais do reino não desapareçam de forma dinâmica."
  #########Kingdorugha 4/9/2020#########
